# Generated by Django 4.0.2 on 2022-02-15 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket_checkout', '0004_alter_discount_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='min_amount',
            field=models.BigIntegerField(default=2, validators=[django.core.validators.MinValueValidator(2)]),
        ),
    ]
