# Generated by Django 4.0.2 on 2022-02-15 17:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket_checkout', '0006_alter_discount_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='min_amount',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='discount',
        ),
        migrations.AddField(
            model_name='discount',
            name='new_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
