# Generated by Django 4.0.2 on 2022-02-15 18:48

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket_checkout', '0008_alter_discount_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='amount',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='shopingbasket',
            name='products',
        ),
        migrations.AddField(
            model_name='shopingbasket',
            name='products',
            field=picklefield.fields.PickledObjectField(default={}, editable=False),
        ),
    ]
