# Generated by Django 4.0.2 on 2022-02-15 19:38

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket_checkout', '0009_rename_amount_discount_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopingbasket',
            name='products',
            field=picklefield.fields.PickledObjectField(default=dict, editable=False),
        ),
    ]
